### ISSUE TITLE
Graphical issues with vanilla background shaders

### ISSUE THREAD

**Issue by Felix14-v2** [gbl/FlightHelper#3]
The configuration menu looks strange with vanilla shaders changes background display.
![image](https://user-images.githubusercontent.com/75726196/136117521-5cf062f0-af4d-4ea3-b05c-fdf03b5dcdbb.png)

**To reproduce**
- Install FlightHelper
- Install resourcepack with background shaders (e.g. [this](https://www.planetminecraft.com/texture-pack/menus-enchanted/))
- Open FlightHelper configs screen
- See graphics issue

This also affects your other mods with the same config screen.

**Comment by gbl** [comment]
Closing this as it doesn't impact the functionality, and new versions use cloth-config anyway.
