### ISSUE TITLE
Suggestion: Configuration for yaw locking, more accurate configuration sliders

### ISSUE THREAD

**Issue by RUTHINAS** [gbl/FlightHelper#4]
For some time now, the population of a server I am hosting has been using Elytra gliding as a way to travel long distances. I recently discovered FlightHelper and have found that the method used is a lot more convenient with the mod.

The method we utilize is one demonstrated by TecThor (https://tecthor.com/elytra-autopilot) and after configuring the mod to the values of -90.0 and -1.0 via editing the flighthelper.json file, it is now a breeze to travel between locations, and previously common issues with overshooting or undershooting the target are mostly a thing of the past. However, FlightHelper's yaw locking is somewhat troublesome, as some of our flight paths between locations are set up with yaw angles close to multiples of 90. By pressing the hotkeys, the yaw jumps to the nearest multiple of 90 as long as it is ≤5° away from the current yaw value. Could this functionality have a toggle in the settings, either via ModMenu or by editing the .json?

The sliders for adjusting the pitch values could do with some redesigning as well. Though I'm not likely to be changing the setting anytime soon, I'm sure it would be convenient for others if the values could be set exactly by inputting a number. Trying to set the value to exactly 1.00° seems impossible on my client. The closest I can get is 0.94°, and the next pixel-jump lands the value at 1.88°

**Comment by gbl** [comment]
I just released a 1.2.2 version which has the "snap yaw" feature toggle-able.
Redesigning the sliders is a bit harder, so, not doing this right now. But as you noted, if you really need them exact, you can set them in the config file.
