### ISSUE TITLE
Inquiry about “Java heap space” error during compilation process

### ISSUE THREAD

**Issue by MagPlum** [gbl/FlightHelper#5]
hello. While trying to compile the FlightHelper mode myself, I am unable to solve the problem on my own, so I am asking for help.
Following the COMPLING.md description in the code, I downloaded gradle and Versionfiles submodule and attempted to compile it. I used gradle 8.3 and java 17 to compile Minecraft 1.20.
I tried increasing the Java heap space from the default maximum of 4GB by 2GB to 10GB, but the build still fails with a “Java heap space” error.
I tried building in Intellij and git bash, but in both cases the build is failing with the same error.

Could you please tell me which version of gradle and java I should use?
Am I configuring my java heap space incorrectly?
How much java heap space should I set?
I am attaching the code I attempted to compile and the error message for reference in troubleshooting.

Thank you always for making and sharing good mods.

[error message.txt](https://github.com/gbl/FlightHelper/files/12639910/error.message.txt)
[FlightHelper-fabric_1_20_failed_with_java_heap_space_error.zip](https://github.com/gbl/FlightHelper/files/12639911/FlightHelper-fabric_1_20_failed_with_java_heap_space_error.zip)

**Comment by gbl** [comment]
As I'm using Linux, there might be some windows stuff going on that I don't know about.
However, I'm using gradle 8.1.1:
```
$ gradle -version

------------------------------------------------------------
Gradle 8.1.1
------------------------------------------------------------

Build time:   2023-04-21 12:31:26 UTC
Revision:     1cf537a851c635c364a4214885f8b9798051175b

Kotlin:       1.8.10
Groovy:       3.0.15
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          17.0.3 (Oracle Corporation 17.0.3+8-LTS-111)
OS:           Linux 5.19.0-43-generic amd64
```

and my global gradle.properties file has:
```
$ cat ~/.gradle/gradle.properties 
org.gradle.jvmargs=-Xmx8G
```
The gradle.properties file should be in your user home directory in .gradle, for example, `C:\Users\RamTamDe\.gradle\gradle.properties`. If you still have problems even with 10 GB of heap space, maybe that file is not where it should be, or the capitalization is wrong, so you're not setting the heap space in the first place?

There are some good answers in https://stackoverflow.com/questions/47454257/how-to-increase-maximum-heap-size-for-the-gradle-daemon - this is about android, but gradle works in the same way. 

Just remember you can have a gradle.properties file in the project directory (you don't in the zip), or in .gradle in your home directory, and in general, especially if you have multiple projects, you want only a single one in your home directory so there's no confusion which one gets used and which one doesn't.

**Comment by MagPlum** [comment]
> As I'm using Linux, there might be some windows stuff going on that I don't know about. However, I'm using gradle 8.1.1:
> 
> ```
> $ gradle -version
> 
> ------------------------------------------------------------
> Gradle 8.1.1
> ------------------------------------------------------------
> 
> Build time:   2023-04-21 12:31:26 UTC
> Revision:     1cf537a851c635c364a4214885f8b9798051175b
> 
> Kotlin:       1.8.10
> Groovy:       3.0.15
> Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
> JVM:          17.0.3 (Oracle Corporation 17.0.3+8-LTS-111)
> OS:           Linux 5.19.0-43-generic amd64
> ```
> 
> and my global gradle.properties file has:
> 
> ```
> $ cat ~/.gradle/gradle.properties 
> org.gradle.jvmargs=-Xmx8G
> ```
> 
> The gradle.properties file should be in your user home directory in .gradle, for example, `C:\Users\RamTamDe\.gradle\gradle.properties`. If you still have problems even with 10 GB of heap space, maybe that file is not where it should be, or the capitalization is wrong, so you're not setting the heap space in the first place?
> 
> There are some good answers in https://stackoverflow.com/questions/47454257/how-to-increase-maximum-heap-size-for-the-gradle-daemon - this is about android, but gradle works in the same way.
> 
> Just remember you can have a gradle.properties file in the project directory (you don't in the zip), or in .gradle in your home directory, and in general, especially if you have multiple projects, you want only a single one in your home directory so there's no confusion which one gets used and which one doesn't.

As you explained, I created a "gradle.properties" file in the C:\Users\userID\\.gradle path and entered "org.gradle.jvmargs=-Xmx8G" and it was resolved immediately. I've been struggling with this problem for a few days, and I'm really grateful that you resolved it. I wish you lots of luck!
